options:
  admins:
    type: string
    default: ""
    description: | 
      Comma separated list of usernames who should be an admin. eg: "codinghorror,sam,eviltrout"
  repository:
    type: string
    default: "https://github.com/discourse/discourse.git"
    description: "Fully qualified git url to repository of discourse application"
  release:
    type: string
    default: "latest-release"
    description: "Git tag (release) of discourse repository. See README.md for additional details"
  branch:
    type: string
    default: "master"
    description: "The git branch to use from `repository`"
  thins:
    type: string
    default: "auto"
    description: |
      Number of thin clients to run, set to auto to have things spun up based on resources, otherwise any positive integer greater than 1
  env:
    type: string
    default: "RUBY_GC_MALLOC_LIMIT=90000000 LD_PRELOAD=/usr/lib/libtcmalloc_minimal.so.0.1.0"
    description: |
      Environment variables used when running the webserver serving Discourse (thin). See README.md for more information
